# Generated by Django 5.1.4 on 2025-01-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mveapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('duration', models.DurationField()),
                ('poster', models.ImageField(upload_to='movies/posters/')),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
