# Generated by Django 5.1.4 on 2025-01-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mveapp', '0002_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='star_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
