# Generated by Django 5.1.4 on 2025-01-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mveapp', '0003_movie_star_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='location',
        ),
        migrations.AddField(
            model_name='movie',
            name='location',
            field=models.ManyToManyField(to='mveapp.location'),
        ),
    ]
