# Generated by Django 5.1.4 on 2025-01-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mveapp', '0004_location_remove_movie_location_movie_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi'), ('Romance', 'Romance')], max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Malayalam', 'Malayalam'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu')], max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='movies/posters/'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='fname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
