# Generated by Django 5.1.4 on 2025-03-03 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mveapp', '0009_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mveapp.registration'),
        ),
    ]
