# Generated by Django 5.1.4 on 2025-03-23 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mveapp', '0014_bookingdetail_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedSnack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_snacks', to='mveapp.bookingdetail')),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mveapp.snack')),
            ],
        ),
    ]
