# Generated by Django 5.1.4 on 2025-03-24 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mveapp', '0015_selectedsnack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetail',
            name='snacks',
        ),
    ]
