# Generated by Django 5.1.4 on 2025-04-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mveapp', '0018_alter_bookingdetail_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetail',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
